// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Int_simt_log_D
double Int_simt_log_D(double x, double lamb, double a);
RcppExport SEXP _neggfl_Int_simt_log_D(SEXP xSEXP, SEXP lambSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lamb(lambSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(Int_simt_log_D(x, lamb, a));
    return rcpp_result_gen;
END_RCPP
}
// mode_kde
double mode_kde(arma::vec points, int T);
RcppExport SEXP _neggfl_mode_kde(SEXP pointsSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(mode_kde(points, T));
    return rcpp_result_gen;
END_RCPP
}
// negfl_bas
Rcpp::List negfl_bas(arma::mat y, arma::mat X, Rcpp::DataFrame hparams, int B);
RcppExport SEXP _neggfl_negfl_bas(SEXP ySEXP, SEXP XSEXP, SEXP hparamsSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type hparams(hparamsSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(negfl_bas(y, X, hparams, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neggfl_Int_simt_log_D", (DL_FUNC) &_neggfl_Int_simt_log_D, 3},
    {"_neggfl_mode_kde", (DL_FUNC) &_neggfl_mode_kde, 2},
    {"_neggfl_negfl_bas", (DL_FUNC) &_neggfl_negfl_bas, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_neggfl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
